### ISSUE TITLE
List of words that do not return a definition

### ISSUE THREAD

**Issue by silverwings15** [sajadhsm/new-word-tab#15]
Update is ongoing

Vendition
Recreancy
Impliable
Opaqueness
Intestacy
Death's-head (displayed as `Death&#039;s-head` in the extension)
Thermoelectricity
Luxuriance
Viceroy
Emaciate
Imperviousness
Discrepant
Redundance
Palpability
Assonant
Achillean
Acarpous
Calvinize
Pinchers
Loiterer
Incandescence
Insuppressible
Behalf
Wretchedness
Discontinuance
Distensible
Vindicatory
Donator
Decameron
Tempter
Incorrigibility
Pledgeor
Irritancy
Effulgence
Protuberate
Inapprehensible
Prehensible
Prudery
Pseudapostle
Seignoir
Intromit
Plebiscitea
Reprehand
Prescriptible
Intromit
Compressible
Efflorescence

Since the migration to Wikitionary API

Dawdler
Gorge
Recrudescent
Detraction
Theocrasy
Univalence
Pungency
Requital

**Comment by sajadhsm** [comment]
Thanks for continuously listing these words. It looks like a never-ending list :))

We need to gradually find definitions for these ones and store them in a JSON similar to the `Free dictionary API` schema.

<details>
<summary>Example</summary>

Required fields are: `word`, `phonetic`, `meanings`

```json
{
  "word": "test",
  "phonetic": "tɛst",
  "phonetics": [
    {
      "text": "tɛst",
      "audio": "..."
    }
  ],
  "origin": "...",
  "meanings": [
    {
      "partOfSpeech": "noun",
      "definitions": [
        {
          "definition": "...",
          "example": "...",
          "synonyms": ["..."],
          "antonyms": ["..."]
        }
      ]
    },
    {
      "partOfSpeech": "verb",
      "definitions": [
        {
          "definition": "...",
          "example": "...",
          "synonyms": ["..."],
          "antonyms": ["..."]
        }
      ]
    }
  ]
}
```
</details>

I don't know which sources should we use yet but it's probably a good idea to also add a `source` property for reference.

I think it's better to then keep them in a separate repository and somehow fetch the list in the extension. Therefore we can easier maintain and update the list without needing a new extension release.

**Comment by silverwings15** [comment]
Hmm, would it even be possible to embed the audio for those entries?

**Comment by sajadhsm** [comment]
Not directly. We need to link to the audio hosted somewhere. The API is using such address for the audios:

`//ssl.gstatic.com/dictionary/static/sounds/20200429/test--_gb_1.mp3`

I'll try to figure out if it's possible to use the same service or find another solution.

BTW we can make phonetic optional since some of the words currently don't show the phonetic in the extension too.

**Comment by silverwings15** [comment]
Yeah i think phonetics is not a must-have if we already have the audio.

I'm reading the free API's Github page, and the dev has stated that he's planning on migrating the source to Wikitionary: https://github.com/meetDeveloper/freeDictionaryAPI/issues/102. However there doesn't seem to have been any progress in the past few months. Maybe we should wait and see how that pans out?

**Comment by silverwings15** [comment]
the freedictionary dev has stated that he completed the migration, but i haven't noticed any changes yet haha

**Comment by sajadhsm** [comment]
Thanks for the update.

There are some changes in the API response which broke the phonetics section in NWT. I'll try to fix those changes and release a new version ASAP. Also, some definitions don't have any example which feels bad :(

Sadly it seems that even the migrated API doesn't return any definition for the list of words in this issue. (But searching the words in the Wiktionary website directly, gives at least a line of definition.)

Whenever I found some more free time, I'll try to see if working with the Wiktionary API directly gives a different result or not.

I think maintaining the definitions by ourself doesn't really worth the effort. So if we didn't find a better solution, we should probably ignore the words that do not return a definition for now!

**Comment by silverwings15** [comment]
> I think maintaining the definitions by ourself doesn't really worth the effort

yeah hard agree on this. i asked the developer of the API about why some words do not return a definition even though their entries exist on wikitionary, will update you again once there's a response

**Comment by silverwings15** [comment]
so first thing first, i went through the word lists and compiled a list of all words that the API currently doesn't return a result for. although by the time i finished, i started questioning how helpful it was given that it's not something EV can fix. 

[words without definition.txt](https://github.com/sajadhsm/new-word-tab/files/8141748/words.without.definition.txt)
.

**Comment by sajadhsm** [comment]
Nice job. I'm wondering why we haven't done it earlier rather than gradually updating the list :))

BTW it seems some words that are listed in the issue are not present in your compiled list, so chances are that there are even more words without definition. (e.g. Pinchers, Wretchedness, Discontinuance, ...)

So I think it's OK to keep the current behavior (link to Google Translate and try another word button). If users are really curios about the definition, they can look it up by themselves. Maybe in the future, we can provide more "Search in X" buttons to make the searching easier.

Should we close the issue for now?

**Comment by silverwings15** [comment]
all three examples you mentioned are all in my big compiled list in the SAT section. i thoroughly went through all of the lists (some 16k+ entries from my rough memory), and while it's always possible i missed a word here and there, i think the list is pretty comprehensive.

the only matter left i can think of with regards to this, is that even when words don't return a definition, the Mark button should still be visible imo.

**Comment by sajadhsm** [comment]
Ops sorry. Yeah, you're right. I was using the Notepad find feature for the first time. It has a direction property that doesn't do a full search. TIL how that works :))

Totally agree with that. So when we mark a word when it has no definition it's actually an ignored word, which you mentioned a while ago. I'll try to add the ignored list and then add the marked as ignore button when a word has no definition.

Probably I'll try to add sort and filter options for the learned and ignored lists to have a better UX.

Once again thanks for your useful suggestions ✌️
