### ISSUE TITLE
Add examples for each word

### ISSUE THREAD

**Issue by DearRude** [sajadhsm/new-word-tab#26]
Having examples can rapidly boost the speed of remembrance.

Thank you for great software.

**Comment by sajadhsm** [comment]
Thanks for the feedback.

The definitions for each word is fetched from [Free Dictionary API](https://github.com/meetDeveloper/freeDictionaryAPI) which uses [Wikidinaty](https://www.wiktionary.org/) behind the scenes.

Therefore unfortunately we don't have full control on the definitions. However, some words include examples. As Wikidinaty data gets richer, NWT will get better too. So contribution on Wikidinaty is very welcome!

<img width="831" alt="Screenshot 2022-09-02 at 16 25 03" src="https://user-images.githubusercontent.com/20022818/188171809-760b99ae-53cd-4c80-9607-c6115c08bdf2.png">
